# Change these first
owner: wwsquared # Your GitHub organization or username, where this repository lives
repo: up # The name of this repository

sites:
  - name: Google - Litmus test
    url: https://www.google.com
  - name: Wikipedia - Litmus Site
    url: https://en.wikipedia.org
  - name: W2Screen
    url: https://w2screen.com
  - name: WW SRC APP
    url: https://src.wellnesswayusa.com
    
  - name: SRCBenefits
    url: https://srcbenefits.com
   - name: SRSO Benefits
    url: https://srsohr.com
   - name: WW SRC APP
    url: https://src.wellnesswaveusa.com
   - name: JO Insurance
    url: https://joservicesinsurance.com
   - name: JSGLOBE
    url: https://joservicesglobal.com
   - name: FirstResponder
    url: https://floridafirstresponders.com
   - name: WellnessWayUSA
    url: https://wellnesswayusa.com
   - name: WW Connect
    url: https://wellnesswayconnect.com
   - name: WW SRC APP
    url: https://src.wellnesswayusa.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /up
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /up
    - title: WWSqurd Uptime
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
