# Change these first
owner: wwsqaured # Your GitHub organization or username, where this repository lives
repo: up # The name of this repository

sites:
  - name: WW 
    url: https://wellnesswayusa.com
  - name: WW SRC APP
    url: https://src.wellnesswaveusa.com
  - name: SRCBenefits
    url: https://srcbenefits.com
  - name: SRSO Benefits
    url: https://srsohr.com
  - name: JO Insurance
    url: https://joservicesinsurance.com
  - name: FirstResponder
    url: https://firstrespondersflorida.com
  - name: WellnessWayUSA
    url: https://wellnesswayusa.com
  - name: WW Connect
    url: https://wellnesswayconnect.com 
  - name: SRCBenefits
    url: https://srcbenefits.com
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /up/
  logoUrl: https://raw.githubusercontent.com/wwsqaured/up/master/assets/upptime-icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /up/
    - title: WWUptime
      href: https://github.com/$OWNER/$REPO/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
